apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: default             # add your namespace
type: Opaque
data:
  mongo-uri: bW9uZ29kYitzcnY6Ly9zaGFua2Fyc2hhbmthcjkwODc3X2RiX3VzZXI6ZmZmaU9qeTRTenBQM0hvckBhaS1yZWNydWl0ZXIuM2FsaW0zZy5tb25nb2RiLm5ldC9qb2JzP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPXJlY3J1aXRlcmFpZGV2   # ✅ only this one key needed