spring:
  application:
    name: Vendor

  data:
    mongodb:
      uri: mongodb://localhost:27017/jobs

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  bucket: ${AWS_BUCKET}

app:
  interview:
    base-url: http://localhost:4200/test/

  hr:
    email: vidya.sagar@hginfotech.io

interview:
  interviewers:
    - id: 1
      name: A
      email: vidyasagarnatikar07@gmail.com
    - id: 2
      name: B
      email: bramhananda.kl@hginfotech.io
    - id: 3
      name: C
      email: c@company.com
    - id: 4
      name: D
      email: d@company.com
      server:
        error:
          include-message=always:

server:
  port: 8081
    
