replicaCount: 2

image:
  repository: shiva9828/ai-recruiter-backend
  tag: v1
  pullPolicy: Always


service:
  type: ClusterIP
  port: 3000


ingress:
  enabled: false


env:
  corsOrigin: "http://localhost:3000"



secret:
  appSecrets:
    jwtSecret: "NzZmOTU5N2FkODg0YTIwZTUzM2JjYzJkOGFjNzk1MTY2ODMyYzQzMDAwOGY3ZWQxM2RmNWYwODllYzNiOWVhYg=="

  mongoSecrets:
    uriSecretName: mongo-secret
    uriSecretKey: mongo-uri
